<?php

/**
 * @file
 * Primary module hooks for slavnews_register module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Alter hook for form, adds additional field's.
 */
function slavnews_weather_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $form['#validate'][] = 'user_register_form_validate';
  }

}

/**
 * Function that validates Phone number.
 */
function user_register_form_validate(&$form, FormStateInterface $form_state) {
  $data = $form_state->getUserInput();
  if (($phoneNum = $data['field_phone']['0']['value']) != '') {
    if (!preg_match('/^\\+?\\d{1,4}?[-.\\s]?\\(?\\d{1,3}?\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$/', $phoneNum)) {
      $form_state->setErrorByName('incorrect_number', 'You have entered invalid phone number.');
    }
  }
}

/**
 * Hook that alter user on registration and adds reader role.
 */
function slavnews_weather_user_presave(EntityInterface $entity) {
  if ($entity->isNew()) {
    $entity->AddRole('reader');
  }
}
